/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frame;

import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author bangkun
 */
public class Karyawan extends javax.swing.JPanel {
    Connection con;
    Statement stm;
    ResultSet rs;
    String sql;
    DefaultTableModel model; 
    
    public Karyawan() {
        initComponents();
        koneksiDB db = new koneksiDB();
        db.connect();
        con = db.connection;
        stm = db.statement;
        tampilkanData();
        kosongkanForm();
        btnsimpan.setEnabled(false);
        btnedit.setEnabled(false);
        btnhapus.setEnabled(false);
    }
    public void kosongkanForm(){
        txkaryawan.setText(null);
        txnama.setText(null);
        txalamat.setText(null);
        txtelepon.setText(null);
        rblaki.setSelected(false);
        rbperempuan.setSelected(false);
    }
    public void tampilkanData(){
        model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Id Karyawan");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");
        model.addColumn("Telepon");
        
        try{
            int no = 1;
            sql = "select * from karyawan";
            ResultSet rs = stm.executeQuery(sql);
            
            while(rs.next()){
                model.addRow(new Object[]{no++, rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
                tbKaryawan.setModel(model);
                
            }
        }catch(SQLException e){
            System.out.println("ERROR : "+e.getMessage());
        }
    }
    public void idOtomatis(){
        
        try {
            sql ="select id_karyawan from karyawan order by id_karyawan desc";
            ResultSet rs = stm.executeQuery(sql);
            if(rs.next()){
                String cekID = rs.getString("id_karyawan").substring(3);
                int AN =Integer.parseInt(cekID)+1;
                String id = Integer.toString(AN);
                String a = String.format("%02d", AN);
                txkaryawan.setText("KAR"+a);
                
            }else{
                txkaryawan.setText("KAR01");                
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txnama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKaryawan = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txalamat = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        txtelepon = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        txcari = new javax.swing.JTextField();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txkaryawan = new javax.swing.JTextField();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("DATA KARYAWAN");

        jLabel4.setText("ALAMAT");

        tbKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKaryawan);

        jLabel5.setText("TELEPON");

        btntambah.setBackground(new java.awt.Color(153, 153, 255));
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnsimpan.setBackground(new java.awt.Color(153, 153, 255));
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        txcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txcariKeyReleased(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(153, 153, 255));
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(153, 153, 255));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel2.setText("ID KARYAWAN");

        jLabel3.setText("NAMA");

        txkaryawan.setEnabled(false);

        buttonGroup1.add(rblaki);
        rblaki.setText("Laki - laki");

        buttonGroup1.add(rbperempuan);
        rbperempuan.setText("Perempuan");

        jLabel6.setText("Jenis Kelamin");

        jLabel7.setText("Cari :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(364, 364, 364)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(28, 28, 28)
                                            .addComponent(txalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txcari, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txkaryawan)
                                            .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rblaki)))
                                .addGap(18, 18, 18)
                                .addComponent(rbperempuan)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btntambah)
                        .addGap(78, 78, 78)
                        .addComponent(btnsimpan)
                        .addGap(56, 56, 56)
                        .addComponent(btnedit)
                        .addGap(77, 77, 77)
                        .addComponent(btnhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(412, 412, 412))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txkaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rblaki)
                    .addComponent(rbperempuan)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah)
                    .addComponent(btnsimpan)
                    .addComponent(btnedit)
                    .addComponent(btnhapus))
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKaryawanMouseClicked
        // TODO add your handling code here:
        txkaryawan.setText(tbKaryawan.getValueAt(tbKaryawan.getSelectedRow(), 1).toString());
        txnama.setText(tbKaryawan.getValueAt(tbKaryawan.getSelectedRow(), 2).toString());
        String jk = tbKaryawan.getValueAt(tbKaryawan.getSelectedRow(), 3).toString();
        
        if(jk.equalsIgnoreCase("Laki-laki")){
            rblaki.isSelected();
        }else if(jk.equalsIgnoreCase("Perempuan")){
            rbperempuan.isSelected();
        }
        
        txalamat.setText(tbKaryawan.getValueAt(tbKaryawan.getSelectedRow(), 4).toString());
        txtelepon.setText(tbKaryawan.getValueAt(tbKaryawan.getSelectedRow(), 5).toString());
        btntambah.setEnabled(false);
        btnedit.setEnabled(true);
        btnhapus.setEnabled(true);
        btnsimpan.setEnabled(true);
        btnsimpan.setText("BATAL");
        
    }//GEN-LAST:event_tbKaryawanMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        if(btntambah.getText().equalsIgnoreCase("TAMBAH")){
            idOtomatis();
            btnsimpan.setText("SIMPAN");
            btntambah.setText("REFRESH");
            btnsimpan.setEnabled(true);
            rblaki.setSelected(true);
        }else if(btntambah.getText().equalsIgnoreCase("REFRESH")){
            DefaultTableModel model = (DefaultTableModel)tbKaryawan.getModel();
            model.setRowCount(0);
            tampilkanData();
            kosongkanForm();
            btntambah.setText("TAMBAH");
            btnsimpan.setEnabled(false);
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
            
        if (btnsimpan.getText().equalsIgnoreCase("BATAL")){
                kosongkanForm();
                btntambah.setEnabled(true);
                btnsimpan.setText("SIMPAN");
                btnsimpan.setEnabled(false);
                btnedit.setEnabled(false);
                btnhapus.setEnabled(false);
                
        }else if(btnsimpan.getText().equalsIgnoreCase("SIMPAN")){
            String jk = null;
            if(rblaki.isSelected()){
                jk = "Laki-laki";
            }else if(rbperempuan.isSelected()){
                jk = "Perempuan";
            }
            try {
                
                btnsimpan.setEnabled(false);
                btntambah.setEnabled(true);
                sql = "insert into karyawan values('"+txkaryawan.getText()+"','"+txnama.getText()+"','"+jk+"','"+txalamat.getText()+"','"+txtelepon.getText()+"')";
                stm.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
                tampilkanData();
                kosongkanForm();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Data gagal disimpan, "+ e.getMessage());
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        
        String jk = null;
        if(rblaki.isSelected()){
            jk = "Laki-laki";
        }else if(rbperempuan.isSelected()){
            jk = "Perempuan";
        }
        try{
            sql = "update karyawan set nama_karyawan='"+txnama.getText()+"',alamat='"+txalamat.getText()+"',jenis_kelamin='"+jk+"',telepon='"+txtelepon.getText()+"' where id_karyawan ='"+txkaryawan.getText()+"'";
            stm.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
            tampilkanData();
            kosongkanForm();
            btnsimpan.setEnabled(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Data gagal diupdate, "+ e.getMessage());
        }
        btntambah.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnedit.setEnabled(false);
        btnhapus.setEnabled(false);
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        btntambah.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnedit.setEnabled(false);
        btnhapus.setEnabled(false);
        try {
            sql = "delete from karyawan where id_karyawan='"+txkaryawan.getText()+"'";
            stm.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            tampilkanData();
            kosongkanForm();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Data gagal dihapus, "+ e.getMessage());
        }
        Admin ad = new Admin();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void txcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txcariKeyReleased
        String cari = txcari.getText();
        TableRowSorter tr = new TableRowSorter(model);
        tbKaryawan.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(cari));                     
    }//GEN-LAST:event_txcariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTable tbKaryawan;
    private javax.swing.JTextField txalamat;
    private javax.swing.JTextField txcari;
    private javax.swing.JTextField txkaryawan;
    private javax.swing.JTextField txnama;
    private javax.swing.JTextField txtelepon;
    // End of variables declaration//GEN-END:variables
}
