/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frame;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author bangkun
 */
public class Member extends javax.swing.JPanel {
    Connection con;
    Statement stm;
    ResultSet rs;
    String sql;
    DefaultTableModel model;
    
    
    public Member() {
        initComponents();
        koneksiDB db = new koneksiDB();
        db.connect();
        con = db.connection;
        stm = db.statement;
        tampilkanData();  
        kosongkanForm();
        btnsimpan.setEnabled(false);
        btnedit.setEnabled(false);
        btnhapus.setEnabled(false);
    }
public void kosongkanForm(){
       
        txmember.setText(null);
        txteam.setText(null);
        txtelepon.setText(null);
       
    }
    public void tampilkanData(){
        model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Id Member");
        model.addColumn("Nama Team");
        model.addColumn("Telepon");
                
        try{
            int no = 1;
            sql = "Select * from member";
            ResultSet rs = stm.executeQuery(sql);
            
            while(rs.next()){
                model.addRow(new Object[]{no++, rs.getString(1),rs.getString(2),rs.getString(3)});
                tbMember.setModel(model);
                
            }
        }catch(SQLException e){
            System.out.println("ERROR : "+e.getMessage());
        }
    }
    public void idOtomatis(){
        
        try {
            sql ="select id_member from member order by id_member desc";
            ResultSet rs = stm.executeQuery(sql);
            if(rs.next()){
                String cekID = rs.getString("id_member").substring(3);
                int AN =Integer.parseInt(cekID)+1;
                String id = Integer.toString(AN);
                String a = String.format("%02d", AN);
                txmember.setText("MB"+a);
                
            }else{
                txmember.setText("MBR01");                
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMember = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txmember = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtelepon = new javax.swing.JTextField();
        txteam = new javax.swing.JTextField();
        txcari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("DATA MEMBER");

        tbMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMemberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMember);

        btnhapus.setBackground(new java.awt.Color(153, 153, 255));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(153, 153, 255));
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnsimpan.setBackground(new java.awt.Color(153, 153, 255));
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btntambah.setBackground(new java.awt.Color(153, 153, 255));
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        jLabel2.setText("ID MEMBER");

        txmember.setEnabled(false);

        jLabel3.setText("TELEPON");

        jLabel4.setText("NAMA TEAM");

        txcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txcariKeyReleased(evt);
            }
        });

        jLabel5.setText("Cari :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txmember, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(jLabel3)
                                .addGap(27, 27, 27)
                                .addComponent(txtelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txteam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btntambah)
                        .addGap(67, 67, 67)
                        .addComponent(btnsimpan)
                        .addGap(67, 67, 67)
                        .addComponent(btnedit)
                        .addGap(77, 77, 77)
                        .addComponent(btnhapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txcari, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txteam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txcari, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah)
                    .addComponent(btnsimpan)
                    .addComponent(btnedit)
                    .addComponent(btnhapus))
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
            btntambah.setEnabled(true);
            btnsimpan.setEnabled(false);
            btnedit.setEnabled(false);
            btnhapus.setEnabled(false);
        try {
            sql = "delete from member where id_member='"+txmember.getText()+"'";
            stm.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            tampilkanData();
            kosongkanForm();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Data gagal dihapus, "+ e.getMessage());
        }
        Admin ad = new Admin();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
            btntambah.setEnabled(true);
            btnsimpan.setEnabled(false);
            btnedit.setEnabled(false);
            btnhapus.setEnabled(false);
            try{
                sql = "update member set id_member='"+txmember.getText()+"',nama_team='"+txteam.getText()+"',no_telp='"+txtelepon.getText()+"' where id_member ='"+txmember.getText()+"'";
                stm.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
                tampilkanData();
                kosongkanForm();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Data gagal diupdate, "+ e.getMessage());
            }
        
        
    }//GEN-LAST:event_btneditActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        btntambah.setEnabled(true);    
        if (btnsimpan.getText().equalsIgnoreCase("BATAL")){
                kosongkanForm();
                btnsimpan.setText("SIMPAN");
                btnsimpan.setEnabled(false);
                btnedit.setEnabled(false);
                btnhapus.setEnabled(false);
                
            }else if(btnsimpan.getText().equalsIgnoreCase("SIMPAN")){
                try {
                sql = "insert into member values('"+txmember.getText()+"','"+txteam.getText()+"','"+txtelepon.getText()+"')";
                stm.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
                tampilkanData();
                kosongkanForm();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Data gagal disimpan, "+ e.getMessage());
            }    
    }
                
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        if(btntambah.getText().equalsIgnoreCase("TAMBAH")){
            idOtomatis();
            btnsimpan.setText("SIMPAN");
            btntambah.setText("REFRESH");
            btnsimpan.setEnabled(true);
        }else if(btntambah.getText().equalsIgnoreCase("REFRESH")){
            
            btntambah.setText("TAMBAH");
            DefaultTableModel model = (DefaultTableModel)tbMember.getModel();
            model.setRowCount(0);
            tampilkanData();
            kosongkanForm();
            btnsimpan.setEnabled(false);
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void tbMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMemberMouseClicked
        txmember.setText(tbMember.getValueAt(tbMember.getSelectedRow(), 1).toString());
        txteam.setText(tbMember.getValueAt(tbMember.getSelectedRow(), 2).toString());
        txtelepon.setText(tbMember.getValueAt(tbMember.getSelectedRow(), 3).toString());
        btntambah.setEnabled(false);
        btnedit.setEnabled(true);
        btnhapus.setEnabled(true);
        btnsimpan.setEnabled(true);
        btnsimpan.setText("BATAL");
    }//GEN-LAST:event_tbMemberMouseClicked

    private void txcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txcariKeyReleased
        String cari = txcari.getText();
        TableRowSorter tr = new TableRowSorter(model);
        tbMember.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(cari));   
    }//GEN-LAST:event_txcariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbMember;
    private javax.swing.JTextField txcari;
    private javax.swing.JTextField txmember;
    private javax.swing.JTextField txteam;
    private javax.swing.JTextField txtelepon;
    // End of variables declaration//GEN-END:variables
}
